# Generated by Django 4.2.25 on 2025-10-29 15:16

import datetime
from django.db import migrations, models
import django.db.models.deletion
import primera_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('primera_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='direccion',
            options={'verbose_name_plural': 'Direcciones'},
        ),
        migrations.AlterModelOptions(
            name='nacionalidad',
            options={'verbose_name_plural': 'Nacionalidades'},
        ),
        migrations.AddField(
            model_name='lector',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True, validators=[primera_app.models.validar_mayoria_edad]),
        ),
        migrations.AlterField(
            model_name='lector',
            name='id_direccion',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='primera_app.direccion'),
        ),
    ]
