# Generated by Django 4.2.25 on 2025-10-29 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('primera_app', '0002_alter_direccion_options_alter_nacionalidad_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='id_categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='primera_app.categoria'),
        ),
    ]
